// Test generated by RoostGPT for test telegramBotTest using AI Type Open AI and AI Model gpt-4

package org.telegram.telegrambots.bots;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.methods.send.SendVideoNote;
import org.telegram.telegrambots.meta.api.objects.Message;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.any;
import static org.mockito.Mockito.when;

public class DefaultAbsSender_execute_e362eaee51_Test {

    @InjectMocks
    private DefaultAbsSender defaultAbsSender;

    @Mock
    private SendVideoNote sendVideoNote;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testExecute_Success() throws TelegramApiException {
        Message expectedMessage = new Message();
        when(sendVideoNote.deserializeResponse(any())).thenReturn(expectedMessage);

        Message actualMessage = defaultAbsSender.execute(sendVideoNote);

        assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testExecute_Failure() throws TelegramApiException {
        when(sendVideoNote.deserializeResponse(any())).thenThrow(new TelegramApiException("Failed to send video note"));

        assertThrows(TelegramApiException.class, () -> defaultAbsSender.execute(sendVideoNote));
    }
}
